#!/bin/bash
# /************************************************************************
# * The MIT License (MIT)
# *
# * Copyright (c) 2019 Bonden i Nol (hakanbrolin@hotmail.com)
# * 
# * Permission is hereby granted, free of charge, to any person obtaining a copy
# * of this software and associated documentation files (the "Software"), to deal
# * in the Software without restriction, including without limitation the rights
# * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# * copies of the Software, and to permit persons to whom the Software is
# * furnished to do so, subject to the following conditions:
# *
# * The above copyright notice and this permission notice shall be included in
# * all copies or substantial portions of the Software.
# *
# * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# * THE SOFTWARE.
# ************************************************************************/

# MCUEXPRESSO setup
MCUXPRESSO_PATH=/usr/local/mcuxpressoide-11.0.1_2563
IDE=${MCUXPRESSO_PATH}/ide/mcuxpressoide
TC_PATH=${MCUXPRESSO_PATH}/ide/tools/bin
export PATH=$PATH:${TC_PATH}

WORKSPACE=/proj2/imxrt/MCUXpresso_11.0.1_2563/workspace

# Default arguments
PROJECT=evkbimxrt1050_freertos_test
CONFIG=Debug-SDRAM
BUILD=build

this=`basename $0`

show_help ()
{
   echo "Usage: $this [--proj=<project name>] [--config=Debug|Debug-SDRAM|Debug-SDRAM-Flash] [--build=build|cleanBuild]"
}

# Parse arguments
for i in "$@"
do
case $i in
    --build=*)
    BUILD="${i#*=}"
    shift # past argument=value
    ;;
    --config=*)
    CONFIG="${i#*=}"
    shift # past argument=value
    ;;
    --proj=*)
    PROJECT="${i#*=}"
    shift # past argument=value
    ;;
    *)
    show_help
    exit
    ;;
esac
done

# Launch IDE in headless mode
${IDE} -nosplash \
       --launcher.suppressErrors \
       -application org.eclipse.cdt.managedbuilder.core.headlessbuild \
       -data ${WORKSPACE} \
       -${BUILD} ${PROJECT}/${CONFIG}
